project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Labor Stats By Gender"
  author:
    - Marissa Inga (mi2548)
    - Victoria Lin (vl2534)
  repo-url: https://github.com/victorialin898/USLaborStatsByGender
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


